/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE RAW_RPM PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* RPM sensor data message.
*/
public class msg_raw_rpm extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_RAW_RPM = 339;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_RAW_RPM;


      
    /**
    * Indicated rate
    */
    public float frequency;
      
    /**
    * Index of this RPM sensor (0-indexed)
    */
    public short index;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_RAW_RPM;
              
        packet.payload.putFloat(frequency);
              
        packet.payload.putUnsignedByte(index);
        
        return packet;
    }

    /**
    * Decode a raw_rpm message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.frequency = payload.getFloat();
              
        this.index = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_raw_rpm(){
        msgid = MAVLINK_MSG_ID_RAW_RPM;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_raw_rpm(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_RAW_RPM;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_RAW_RPM - sysid:"+sysid+" compid:"+compid+" frequency:"+frequency+" index:"+index+"";
    }
}
        