/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GIMBAL_MANAGER_SET_TILTPAN PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* High level message to control a gimbal's tilt and pan angles. This message is to be sent to the gimbal manager (e.g. from a ground station). Angles and rates can be set to NaN according to use case.
*/
public class msg_gimbal_manager_set_tiltpan extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN = 287;
    public static final int MAVLINK_MSG_LENGTH = 23;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN;


      
    /**
    * High level gimbal manager flags to use.
    */
    public long flags;
      
    /**
    * Tilt/pitch angle (positive: up, negative: down, NaN to be ignored).
    */
    public float tilt;
      
    /**
    * Pan/yaw angle (positive: to the right, negative: to the left, NaN to be ignored).
    */
    public float pan;
      
    /**
    * Tilt/pitch angular rate (positive: up, negative: down, NaN to be ignored).
    */
    public float tilt_rate;
      
    /**
    * Pan/yaw angular rate (positive: to the right, negative: to the left, NaN to be ignored).
    */
    public float pan_rate;
      
    /**
    * System ID
    */
    public short target_system;
      
    /**
    * Component ID
    */
    public short target_component;
      
    /**
    * Component ID of gimbal device to address (or 1-6 for non-MAVLink gimbal), 0 for all gimbal device components. (Send command multiple times for more than one but not all gimbals.)
    */
    public short gimbal_device_id;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN;
              
        packet.payload.putUnsignedInt(flags);
              
        packet.payload.putFloat(tilt);
              
        packet.payload.putFloat(pan);
              
        packet.payload.putFloat(tilt_rate);
              
        packet.payload.putFloat(pan_rate);
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(target_component);
              
        packet.payload.putUnsignedByte(gimbal_device_id);
        
        return packet;
    }

    /**
    * Decode a gimbal_manager_set_tiltpan message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.flags = payload.getUnsignedInt();
              
        this.tilt = payload.getFloat();
              
        this.pan = payload.getFloat();
              
        this.tilt_rate = payload.getFloat();
              
        this.pan_rate = payload.getFloat();
              
        this.target_system = payload.getUnsignedByte();
              
        this.target_component = payload.getUnsignedByte();
              
        this.gimbal_device_id = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_gimbal_manager_set_tiltpan(){
        msgid = MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_gimbal_manager_set_tiltpan(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN;
        unpack(mavLinkPacket.payload);        
    }

                    
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_TILTPAN - sysid:"+sysid+" compid:"+compid+" flags:"+flags+" tilt:"+tilt+" pan:"+pan+" tilt_rate:"+tilt_rate+" pan_rate:"+pan_rate+" target_system:"+target_system+" target_component:"+target_component+" gimbal_device_id:"+gimbal_device_id+"";
    }
}
        